# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: dev
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
        
      #- name: Test
        #run: dotnet test --no-build --verbosity normal

    - name: Publish win-x64
      run: dotnet publish "/home/runner/work/Simple-Icon-File-Maker/Simple-Icon-File-Maker/Simple Icon File Maker/Simple Icon File Maker.csproj" -c Release -r win10-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true -p:PublishReadyToRun=false

    - name: Create win client archive
      run: |
        cd "/home/runner/work/Simple-Icon-File-Maker/Simple-Icon-File-Maker/bin/Release/net8.0/win10-x64/publish/" && zip -r client-win-x64.zip *
  
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
  
    - name: Create Release
      id: create_release
      uses: elgohr/Github-Release-Action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ steps.date.outputs.date }}
        release_name: Release ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false
  
    - name: Upload Client win10-x64 Asset
      id: upload-release-client-win-asset 
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "/home/runner/work/Simple-Icon-File-Maker/Simple-Icon-File-Maker/Simple Icon File Maker/bin/Release/net8.0/win10-x64/publish/client-win-x64.zip"
        asset_name: client-win-x64.zip
        asset_content_type: application/zip
    
